### ISSUE TITLE
Issue with TAL

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-Shuttle_OPS1#10]
![Kerbal Space Program Screenshot 2024 03 31 - 21 06 58 59](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/280c0988-9770-462c-8dfa-21af9a30fc0c)
been having issues with tal

**Comment by XEridaniTribalX** [comment]
I am also having the exact same issue with the TAL abort, with that exact same error. I did find out though that if I uncomment the line that forces Zaragoza as the TAL site in the script, it does work correctly. It's just not working for the random selection based on what is in range.
![Troubleshooting](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/20619014/8c0838a4-ecda-4105-855b-1afbc5f9676e)

**Comment by giuliodondi** [comment]
It was essentially the same bug as (https://github.com/giuliodondi/kOS-Shuttle_OPS1/issues/8), it was already fixed in the dev branch but it's not ready to be merged yet.

I pushed a hotfix on master which should sort it out for the moment
