### ISSUE TITLE
For ATO Abort about OMS Dump

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-Shuttle_OPS1#11]
shouldnt there be an oms dump for the aj-10 just like what happened in sts-51f: https://en.wikipedia.org/wiki/STS-51-F

**Comment by giuliodondi** [comment]
I deliberately chose not to do the automatic OMS dump in the ATO / AOA case for two reasons:

- it's not needed performance-wise: the logic that predicts the abort boundaries only accounts for SSME thrusting. So if you have ATO available you can do it without OMS
- You need all the OMS you have to do orbital corrections if you want to do an abort once around or raise the orbit
