### ISSUE TITLE
out of range exception

### ISSUE THREAD

**Issue by JovietUnion** [giuliodondi/kOS-Shuttle_OPS1#13]
![image](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/62820134/d7c4bf36-1714-4d84-b2c0-a494e31f0d33)

**Comment by FlandreScarlet1** [comment]
all ssme need the same variant for it to work

**Comment by giuliodondi** [comment]
correct,

nevertheless it's a useful bug report because there's supposed to be a clearer error message when that situation happens

**Comment by JovietUnion** [comment]
I think the SSMEs are the exact same version
[RS-25D-E]

**Comment by giuliodondi** [comment]
Would you mind posting a screenshot proving that the three SSME version is the same and nevertheless the problem persists?

**Comment by JovietUnion** [comment]
When I get home in an hour, yes

**Comment by JovietUnion** [comment]
![Screenshot 2024-05-06 145203](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/62820134/28c3b2ef-4056-4c19-aa39-4645a0de413b)

**Comment by giuliodondi** [comment]
are you using RO engines?

**Comment by JovietUnion** [comment]
Yes I am

**Comment by JovietUnion** [comment]
Delete ROEngines?

**Comment by giuliodondi** [comment]
nah this issue has arisen a few times before and it's time I address it, I hope I'll have pushed a fix by tomorrow

**Comment by JovietUnion** [comment]
![image](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/62820134/cf10f12b-46d7-460a-b28b-5c5062beeb31)

Shuttle launched succesfully, but the SRBS hit the external tank.

Tried using ops3 to contingency abort but it gave me this error.

**Comment by giuliodondi** [comment]
you posted two new issues, one about the SpaceShuttleSystem mod and one about the OPS3 program. Neither of which belongs here.

You need to help me keep problems distinct otherwist it's impossible to figure out what solves what
