### ISSUE TITLE
problem with timing 

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-Shuttle_OPS1#15]
ato meco and two engine tal is happening all together: 
![Kerbal Space Program Screenshot 2024 06 24 - 19 17 10 87](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/04f7dad0-ce46-4add-9271-fe133be9742c)

**Comment by FlandreScarlet1** [comment]
![Uploading Kerbal Space Program Screenshot 2024.06.24 - 19.17.10.87.png…]()

**Comment by FlandreScarlet1** [comment]
![Uploading Kerbal Space Program Screenshot 2024.06.24 - 19.17.10.87.png…]()

**Comment by giuliodondi** [comment]
Where are you launching from and what is your mission script?

**Comment by FlandreScarlet1** [comment]
using ops1:

 @LAZYGLOBAL OFF.


//Launch Settings

GLOBAL target_orbit IS LEXICON (	
								"periapsis",50,
								"apoapsis",280,
								"cutoff alt",120,
								"inclination",51.6
).


GLOBAL logdata Is true.


RUNPATH("0:/Shuttle_OPS1/src/ops1_main_executive"). 


launching from cape canaveral lc-39a and i updated ops3 with the latest version the merge dev branch

**Comment by FlandreScarlet1** [comment]
nvm i found the issue fixed the external fuel tank was the main root part and i set the shuttle as the root part and it works
![Kerbal Space Program Screenshot 2024 06 25 - 11 31 19 52](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/e81edd16-b287-4a2c-b254-2eccc738747f)
