### ISSUE TITLE
tends to gimbal right and left 

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-Shuttle_OPS1#16]
during rtls and turn back it tends to gimbal right and left violently and its tends to not like to stabilize straight in ato as well when meco
![Kerbal Space Program Screenshot 2024 06 27 - 11 07 38 61](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/36ebeacb-c327-416f-88f3-866d0fe12bb1)
![Kerbal Space Program Screenshot 2024 06 27 - 11 07 30 32](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/3909232e-8844-4a46-993b-2d9dccc755cc)
@
![Kerbal Space Program Screenshot 2024 06 27 - 11 07 22 77](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/9ae39545-4ed7-48dc-9336-a07b6a826703)

**Comment by giuliodondi** [comment]
it's because you shut down the center engine.

This is a known issue and one that I don't know how to fix yet. If you use the engine failure functionality of the GUI there are protections to avoid just this situation
