### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Potatohog41** [giuliodondi/kOS-Shuttle_OPS1#17]
So i downloaded everything and put the scripts in the ships folder in the main game folder but when i load up kos i get this message
![image_2024-06-28_100743215](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/174123932/729ae94d-a290-4706-9b3b-4d0585c6378c)

**Comment by giuliodondi** [comment]
you need to switch to volume 0 (the archive) before that or else kOS will not read the files form the master directory.
[More information over in the kOS manual](https://ksp-kos.github.io/KOS/commands/files.html#files)
