### ISSUE TITLE
Error during ET Sep

### ISSUE THREAD

**Issue by GlebKerman** [giuliodondi/kOS-Shuttle_OPS1#18]
During ET Sep, I get an error which also saturates the orbiter's RCS
![unknown_2024 07 03-14 51](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/147939419/85042c73-fca1-4329-afd7-e30d6c7339e8)
![unknown_2024 07 03-15 07](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/147939419/b596f1f4-aa75-4bf5-82c8-244ae6171fbc)

**Comment by GlebKerman** [comment]
Posted this in the Ops 3 repo by mistake, apologies for that one

**Comment by giuliodondi** [comment]
The reason the RCS is stuck is that the script commands the translation manoruvre and then crashes before stopping it. The way to do it manually is to run 'SET SHIP:CONTROL:NEUTRALIZE TO TRUE.'

As to why it crashes in the first place, I'll have to investigate. It would be helpful to see the full message, if you coul take another screenshot but with the terminal window much bigger than that

**Comment by GlebKerman** [comment]
I'll try to but I have no idea how to reproduce the error, as far as I'm aware it happens at random

**Comment by giuliodondi** [comment]
well, how often does it appear? Have you tried updating the latest scripts?

I'd like to see the full message but what little I can read so far is already puzzling. First, the code lines in the terminal do not match the source code, second, the program isn't even supposed to land in the block of code that does the function call to get_shuttle_res_left.

**Comment by GlebKerman** [comment]
Hey, it tended to happen right after loading up a quicksave or reverting to launch, I can't tell you if this was a factor in causing the error but just in case installed the latest version of the script and after 10+ launches (and reverts) it seems to have fixed itself as I have been unable to get the error to happen

**Comment by giuliodondi** [comment]
I'm closing the issue since you reported nothing further. If the problem arises again, you can comment here and I'll re-open
