### ISSUE TITLE
way too early ato and meco bug possibly

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-Shuttle_OPS1#19]
timing for them is 3 minutes its a bit early i think by a lot 
![Kerbal Space Program Screenshot 2024 07 27 - 22 21 58 71](https://github.com/user-attachments/assets/5c3e72a8-11df-4abf-9fe6-56bb63501f3c)

**Comment by FlandreScarlet1** [comment]
something else i notice for ato sometimes is also trajectory line is off and press to ato is pressed before the circle thing touches ATO of course

**Comment by giuliodondi** [comment]
I need to know your launch parameters and payload so I can reproduce this.

also the display an markers will always be a little off, thery're just rough indicators, all calculations are done live by the program

**Comment by FlandreScarlet1** [comment]
nvm gulio it was my part on my end i figured it out seems like the shuttle didnt have payload or anything so im guessing thats probably why

**Comment by giuliodondi** [comment]
no wonder, the D variant was intended to lift 15 tons to 52° inclination, not really used for an empty Orbiter to 28°
