### ISSUE TITLE
OPS1 Guidance kOS failure on initiation.

### ISSUE THREAD

**Issue by Lirimi06** [giuliodondi/kOS-Shuttle_OPS1#22]
I entered the flight scene, and entered the following into kOS:
switch to 0.
run ops1. 

The OPS1 guidance screen appeared, starting at the count from 10. The engine throttle was set to max, and about 3 seconds later, kOS fails with the error seen in the screenshot. I performed a reinstallation of the ferram fork, shuttle fork, and all the scripts (ops1 and ops3), and rebuilt the shuttle orbiter to the specifications in the README to make sure.
I also attached my Ships/Script folder just in case I did something wrong. Thank you in advance for your help!

![20241120222100_1](https://github.com/user-attachments/assets/3475836a-7e92-4549-a6f1-9b5e4827d41f)

![Script 11_20_2024 10_26_47 PM](https://github.com/user-attachments/assets/46c3aefe-4150-4957-a88d-ba76c0c9dc55)

**Comment by giuliodondi** [comment]
the error suggests that you're missing the kOS-Ferram dependency.
Please double-check that everything is installed correctly

**Comment by Lirimi06** [comment]
Will do!

**Comment by Lirimi06** [comment]
Works fine now! Thank you!
