### ISSUE TITLE
hello giulio

### ISSUE THREAD

**Issue by GAMETROX50** [giuliodondi/kOS-Shuttle_OPS1#23]
Hello Giulio, I had this problem with ops1, I did a clean installation and I get this error, configure the ship as best as possible and I still suffer from this error with ops1.
![Captura de pantalla 2024-11-25 215855](https://github.com/user-attachments/assets/b6383235-62e8-4e66-a021-3f564060ebf5)

**Comment by giuliodondi** [comment]
the error is truncated by the terminal window, I can't know what your problem is.
Post another screenshot with a larger terminal so the error is not truncated

**Comment by GAMETROX50** [comment]
ok here is the screenshot
![Uploading imagen_2024-11-26_174211957.png…]()

**Comment by GAMETROX50** [comment]
![imagen_2024-11-26_174258894](https://github.com/user-attachments/assets/f034f3cf-4fd6-4469-964b-37beb66977aa)

**Comment by giuliodondi** [comment]
You didn't understand me:

![image](https://github.com/user-attachments/assets/638c79b9-9bc1-44bf-b071-2c6ed23e5438)

this is the terminal window, this is where I see what the problem is. This is what you need to make bigger so I can read the error

**Comment by GAMETROX50** [comment]
![Uploading imagen_2024-11-27_162007631.png…]()

**Comment by GAMETROX50** [comment]
![Uploading imagen_2024-11-27_162449016.png…]()

**Comment by GAMETROX50** [comment]
![Uploading Captura de pantalla 2024-11-27 162000.png…]()

**Comment by giuliodondi** [comment]
whatever you intended to post, it's broken and links to the beginning of the issue

**Comment by GAMETROX50** [comment]
![Captura de pantalla 2024-11-27 162000](https://github.com/user-attachments/assets/a3575a01-3690-4cf0-886d-5ba81f12edb6)

**Comment by GAMETROX50** [comment]
there is the screenshot

**Comment by giuliodondi** [comment]
You still do not understand. You don't need to make the screenshot bigger, I don't have trouble seeing.

![image](https://github.com/user-attachments/assets/cc761c90-6679-4be3-bbef-b30adc548109)

Read what I circled out. Does it look like the beginning of a sentence? 
It is not. There's stuff before it that got truncated out .
You need to enlarge the window in-game before running the script so all the error text can fit in. 

Until you give me the complete error message I can't help you

**Comment by GAMETROX50** [comment]
![Captura de pantalla 2024-12-03 190738](https://github.com/user-attachments/assets/d24d2a72-ac1b-411b-987c-dafe84dd3690)

**Comment by GAMETROX50** [comment]
So?
