### ISSUE TITLE
OPS1 crash during launch

### ISSUE THREAD

**Issue by DreamcastERA1** [giuliodondi/kOS-Shuttle_OPS1#24]
I loaded at ksc and entered the following into kOS:
switch to 0.
run ops1.

The Gui appeared, a 10s countdown started, the main engines ignited, SRBs ignited, but at t+00s script just crashed. (kOS screenshot attached)
I double checked the shuttle configuration, checked scripts, checked ksp language settings everywhere(dictionary.cfg, settings.cfg, BuildID64.txt). Everything seems fine.

Additionally, i didnt change the target orbit.

![image](https://github.com/user-attachments/assets/0cf811dc-af6a-435f-abfa-ec12c98fa712)

i've attached scripts folder screenshot in case i did something wrong. Thank you for your help.

![image](https://github.com/user-attachments/assets/ef4871b5-3f77-4c65-a3b2-6f3349a8759c)
![image](https://github.com/user-attachments/assets/4705ad83-2b45-44ca-b828-260d6cb160ad)

**Comment by giuliodondi** [comment]
I think it's an issue related to data logging: try setting 'logdata' to false in the launch script.

Are you playing career mode or have you configured 'realistic' kOS behaviour in any way? I play sandbox so my kOS has no trouble reading and writing anywhere

**Comment by DreamcastERA1** [comment]
ill try.

No,i was playing sandbox too

**Comment by DreamcastERA1** [comment]
Yea, it worked, thank you
