### ISSUE TITLE
RTLS Problem

### ISSUE THREAD

**Issue by FlandreScarlet1** [giuliodondi/kOS-Shuttle_OPS1#5]
![Kerbal Space Program Screenshot 2023 11 14 - 19 26 02 55](https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/142283370/964dd1b9-7882-4dd8-9d0a-86450f7f5bab)
for some reason i get this error you know maybe why?

**Comment by giuliodondi** [comment]
sneaky bug, it's my fauly. It's now fixed on the master branch
