### ISSUE TITLE
Script crash upon running shuttle.ks

### ISSUE THREAD

**Issue by Evie-dev** [giuliodondi/kOS-Shuttle_OPS1#8]
Using the most recent commits on the master branches of OPS1 and OPS3, installed to a clean ships/script directory, running shuttle.ks provides the following error:
<img width="240" alt="image" src="https://github.com/giuliodondi/kOS-Shuttle_OPS1/assets/153245595/8c3d325e-1cad-4101-b19b-ca512e03d29a">

**Comment by giuliodondi** [comment]
I believe the bug should be fixed now, please pull the ascent script from master and try on your end

**Comment by Evie-dev** [comment]
works on my end too now
